"""add JWT Token

Revision ID: 06a239c84f93
Revises: 3866669e56cd
Create Date: 2023-10-23 19:31:32.525559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a239c84f93'
down_revision = '3866669e56cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ponto',
    sa.Column('id_ponto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_ponto')
    )
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ponto_nome'), ['nome'], unique=True)

    op.create_table('segmento',
    sa.Column('id_segmento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distancia', sa.Integer(), nullable=True),
    sa.Column('ponto_inicial', sa.Integer(), nullable=True),
    sa.Column('ponto_final', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('direcao', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id_segmento')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('segmento')
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ponto_nome'))

    op.drop_table('ponto')
    # ### end Alembic commands ###
