"""empty message

Revision ID: 1b500ebce696
Revises: 
Create Date: 2023-11-29 22:57:19.672102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b500ebce696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ponto',
    sa.Column('ponto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ponto_id')
    )
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ponto_nome'), ['nome'], unique=True)

    op.create_table('segmento',
    sa.Column('segmento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distancia', sa.Float(), nullable=True),
    sa.Column('ponto_inicial', sa.Integer(), nullable=True),
    sa.Column('ponto_final', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('direcao', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('segmento_id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=False)

    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registro', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=True),
    sa.Column('nome', sa.String(length=128), nullable=True),
    sa.Column('tipo_usuario', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuario_registro'), ['registro'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_registro'))
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))

    op.drop_table('token_blocklist')
    op.drop_table('segmento')
    with op.batch_alter_table('ponto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ponto_nome'))

    op.drop_table('ponto')
    # ### end Alembic commands ###
